# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ljwcodeHeadLineNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ljwcodeHeadLineNews
pod 'AFNetworking'
pod 'YYCache'
pod 'DZNEmptyDataSet'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'ReactiveObjC'
pod 'MJRefresh'
pod 'Masonry'
pod 'YYText'
pod 'FMDB'
pod 'LBPhotoBrowser', '~> 2.2.2'
pod 'SDWebImage/WebP'
pod 'SDWebImage’,’~> 4.0.0’
pod 'SDAutoLayout', '~> 2.2.1'
end
