# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'ljwcodeHeadLineNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ljwcodeHeadLineNews
pod 'AFNetworking'
pod 'YYCache'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'ReactiveObjC'
pod 'MJRefresh'
pod 'Masonry'
pod 'YYText'
pod 'SDWebImage/WebP'
pod 'SDWebImage’,’~> 4.0.0’
pod 'DouyinOpenSDK'
pod 'WechatOpenSDK'
pod 'PromisesObjC'
pod 'FMDB', '~> 2.7.5'
end
